"""empty message

Revision ID: 2d2ad20a7e73
Revises: 
Create Date: 2025-07-30 20:59:21.817320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2ad20a7e73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('ist_id', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('roles', sa.String(), nullable=False),
    sa.Column('member_number', sa.Integer(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('join_date', sa.String(), nullable=True),
    sa.Column('exit_date', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ist_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'INACTIVE', 'UNDEFINED', name='projectstateenum', native_enum=False), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('members')
    # ### end Alembic commands ###
