"""init migration

Revision ID: 4d286a329466
Revises: 
Create Date: 2024-11-17 03:37:52.272638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d286a329466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('ist_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('member_number', sa.Integer(), nullable=True),
    sa.Column('join_date', sa.String(), nullable=True),
    sa.Column('exit_date', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extra', sa.String(), nullable=True),
    sa.Column('roles', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('ist_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('member_projects',
    sa.Column('member_username', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('entry_date', sa.String(), nullable=False),
    sa.Column('contributions', sa.String(), nullable=True),
    sa.Column('exit_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['member_username'], ['members.username'], ),
    sa.ForeignKeyConstraint(['project_name'], ['projects.name'], ),
    sa.PrimaryKeyConstraint('member_username', 'project_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_projects')
    op.drop_table('projects')
    op.drop_table('members')
    # ### end Alembic commands ###
