"""add tasks

Revision ID: 96a19a53749c
Revises: 85b198058c96
Create Date: 2025-09-06 12:39:18.836429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a19a53749c'
down_revision = '85b198058c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('join_date', sa.String(), nullable=False),
    sa.Column('roles', sa.String(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'project_id', name='uq_member_project')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_type', sa.Enum('PJ', 'PCC', 'PS', name='pointtypeenum', native_enum=False), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('participation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participation_id'], ['project_participations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project_participation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_participation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('join_date', sa.VARCHAR(), nullable=False),
    sa.Column('roles', sa.VARCHAR(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'project_id', name=op.f('uq_member_project'))
    )
    op.drop_table('tasks')
    op.drop_table('project_participations')
    # ### end Alembic commands ###
