name: docs

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync 

    - name: Generate API docs
      run: uv run sphinx-apidoc -o docs/api-reference/generated . --separate

    - name: Build HTML
      run: uv run make -C docs html

    - name: Push to build branch
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git checkout --orphan docs-build
        git --work-tree docs/_build/html add --all
        git --work-tree docs/_build/html commit -m "Update docs [skip ci]"
        git push origin HEAD:docs-build --force
